#!/bin/bash

usage() {
	echo "Usage: $0 output_dir git_dir"
	echo "output_dir: Directory resultant files should go"
	echo "git_dir: OPTIONAL Directory to obtain git information"
	exit 0
}

if [ -z "${1:-}" ]; then
	usage
fi

# Git directory functionality will be added later
if [ -v "${2:-}" ]; then
	echo "Git information not implemented, continuing without..."
fi

OUTPUT_DIR="$1"

create_nodes() {
	local nodes_location="${OUTPUT_DIR}/buildinfo-nodes/"
	cat "$(date)" >> "${nodes_location}/timestamp"
}
