#!/bin/bash
#
# Setup environment for gui
#

GUI_DEVICES=("/dev/dri/card0" "/dev/dri/renderD128" "/dev/dri/card1")

start() {
	echo "Applying video settings"
	/etc/init.d/S40xorg stop
	for device in "${GUI_DEVICES[@]}"; do
		chmod 777 "$device"
	done
}
stop() {
	echo "Returning video settings to defaults"
	for device in "${GUI_DEVICES[@]}"; do
		chmod 266 "$device"
	done
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
