name: build-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: sudo apt-get install -y splint

    - run: ./checker

  build-minimal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: ./builder actions_run rpi4-arcade-min

    - run: ls builds/

    - run: ls builds/rpi4-arcade-min/

    - run: ls builds/rpi4-arcade-min/output/

    - run: ls builds/rpi4-arcade-min/output/images/

    - uses: actions/upload-artifact@v3
      with:
        name: sd-image-min
        path: builds/rpi4-arcade-min/output/images/*
        if-no-files-found: error

  build-normal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: ./builder actions_run rpi4-arcade

    - uses: actions/upload-artifact@v3
      with:
        name: sd-image
        path: builds/rpi4-arcade/output/images/*
        if-no-files-found: error

  build-developer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: ./builder actions_run rpi4-arcade-dev

    - uses: actions/upload-artifact@v3
      with:
        name: sd-image-dev
        path: builds/rpi4-arcade-dev/output/images/*
        if-no-files-found: error
