name: build-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-minimal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build rpi4 Minimal
      run: ./builder actions_run rpi4-arcade-min

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: sd-image-min
        path: images/sdcard.img

  build-normal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build rpi4 Normal
      run: ./builder actions_run rpi4-arcade

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: sd-image
        path: images/sdcard.img

  build-developer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build rpi4 Developer
      run: ./builder actions_run rpi4-arcade-dev

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: sd-image-dev
        path: images/sdcard.img
